radius = float(input("Enter the radius of the circle: "))
diameter = round(2*radius, 2)
circumference = round(2*3.14*radius, 3)
area = round(3.14*radius**2, 3)
print(f"Details of the circle:\nRadius = {radius}\nDiameter = {diameter}\nCircumference = {circumference}\nArea = {area}")