coordinates = (4, 5, 8)
coordinates2 = ((4, 5), (8, 9))  # Tuples are Immutable (cannot be modified)
print(coordinates)
print(coordinates[2])
print(coordinates2)
print(coordinates2[1])
print("Thus, tuples are basically a data structure like lists but are immutable.")
